In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('transactions_bestsect.csv')

In [2]:
df.head(50)

    id ticker  amount      price        date  type    exp_date        profit
0    1    IYZ   31946  31.301876  2017-01-02   buy  2017-01-09      0.000000
1    1    IYZ   31946  31.170385  2017-01-09  sell  2017-01-09  -4200.602139
2    2    XLY   12544  79.381073  2017-01-09   buy  2017-01-16      0.000000
3    2    XLY   12544  79.352684  2017-01-16  sell  2017-01-16   -356.111328
4    3    XLP   21686  45.902142  2017-01-16   buy  2017-01-23      0.000000
5    3    XLP   21686  45.727535  2017-01-23  sell  2017-01-23  -3786.512726
6    4    XLB   20718  47.863838  2017-01-23   buy  2017-01-30      0.000000
7    4    XLB   20718  47.202198  2017-01-30  sell  2017-01-30 -13707.860985
8    5    XLV   14914  65.568977  2017-01-30   buy  2017-02-06      0.000000
9    5    XLV   14914  65.972923  2017-02-06  sell  2017-02-06   6024.449493
10   6    XLI   16665  59.042652  2017-02-06   buy  2017-02-13      0.000000
11   6    XLI   16665  60.100731  2017-02-13  sell  2017-02-13  17632.882633
12   7    XLF   45156  22.180862  2017-02-13   buy  2017-02-20      0.000000
13   7    XLF   45156  22.135542  2017-02-20  sell  2017-02-20  -2046.492989
14   8    XLU   22809  43.821327  2017-02-20   buy  2017-02-27      0.000000
15   8    XLU   22809  43.761868  2017-02-27  sell  2017-02-27  -1356.215984
16   9    XLF   44101  22.634089  2017-02-27   buy  2017-03-06      0.000000
17   9    XLF   44101  22.470928  2017-03-06  sell  2017-03-06  -7195.533453
18  10    XLK   19867  49.880474  2017-03-06   buy  2017-03-13      0.000000
19  10    XLK   19867  50.096493  2017-03-13  sell  2017-03-13   4291.643051
20  11    IYZ   34169  29.128014  2017-03-13   buy  2017-03-20      0.000000
21  11    IYZ   34169  28.128733  2017-03-20  sell  2017-03-20 -34144.430082
22  12    XLU   21642  44.411121  2017-03-20   buy  2017-03-27      0.000000
23  12    XLU   21642  43.914719  2017-03-27  sell  2017-03-27 -10743.148109
24  13    XLE   17145  55.433105  2017-03-27   buy  2017-04-03      0.000000
25  13    XLE   17145  55.797882  2017-04-03  sell  2017-04-03   6254.095001
26  14    IYZ   32577  29.366007  2017-04-03   buy  2017-04-10      0.000000
27  14    IYZ   32577  29.551649  2017-04-10  sell  2017-04-10   6047.667332
28  15   XLRE   35178  27.366365  2017-04-10   buy  2017-04-17      0.000000
29  15   XLRE   35178  27.588234  2017-04-17  sell  2017-04-17   7804.890621
30  16    XLI   16193  59.934174  2017-04-17   buy  2017-04-24      0.000000
31  16    XLI   16193  60.786304  2017-04-24  sell  2017-04-24  13798.555500
32  17    XLV   14149  69.566048  2017-04-24   buy  2017-05-01      0.000000
33  17    XLV   14149  69.999107  2017-05-01  sell  2017-05-01   6127.361588
34  18    XLF   45670  21.686813  2017-05-01   buy  2017-05-08      0.000000
35  18    XLF   45670  21.432098  2017-05-08  sell  2017-05-08 -11632.832489
36  19    XLK   18685  52.382473  2017-05-08   buy  2017-05-15      0.000000
37  19    XLK   18685  52.080784  2017-05-15  sell  2017-05-15  -5637.061729
38  20   XLRE   35885  27.118893  2017-05-15   buy  2017-05-22      0.000000
39  20   XLRE   35885  27.306633  2017-05-22  sell  2017-05-22   6737.061596
40  21    XLU   21440  45.703480  2017-05-22   buy  2017-05-29      0.000000
41  21    XLU   21440  46.456650  2017-05-29  sell  2017-05-29  16147.965088
42  22    IYZ   33555  29.684250  2017-05-29   buy  2017-06-05      0.000000
43  22    IYZ   33555  29.472094  2017-06-05  sell  2017-06-05  -7118.904505
44  23    XLF   44756  22.096167  2017-06-05   buy  2017-06-12      0.000000
45  23    XLF   44756  22.096167  2017-06-12  sell  2017-06-12      0.000000
46  24    XLI   15714  62.930420  2017-06-12   buy  2017-06-19      0.000000
47  24    XLI   15714  62.611462  2017-06-19  sell  2017-06-19  -5012.110451
48  25    XLV   13217  74.439857  2017-06-19   buy  2017-06-26      0.000000
49  25    XLV   13217  73.302025  2017-06-26  sell  2017-06-26 -15038.734024

In [3]:
df['Positive_return']=np.select([df['profit']>0 ,(df['profit']==0) & (df.type=='buy'),
                                 (df['profit']==0) & (df.type=='sell'),df['profit']<0],[1,None,-1,-1])

In [4]:
df.Positive_return.value_counts(dropna=False)

 NaN    262
 1.0    151
-1.0    110
Name: Positive_return, dtype: int64

In [5]:
df.loc[ (df.Positive_return!=1)&(df.Positive_return!=-1) ].type.value_counts()

buy    262
Name: type, dtype: int64

In [6]:
type(df.iloc[0].profit)

numpy.float64

In [7]:
#df.drop(columns='Positive_return')

In [8]:
tickers=df.ticker.unique().tolist()

In [9]:
tickers

['XLY', 'XLP', 'XLB', 'XLV', 'XLI', 'XLF', 'XLU', 'XLK', 'IYZ', 'XLE', 'XLRE']

In [10]:
occurences=[]
tick_prof=[]
avg_tick_profit=[]
profitable=[]
for ticker in tickers:
    occurence=len(df.loc[df.ticker==ticker])/2
    occurences.append(occurence)
    tot_profit=round(df.loc[df.ticker==ticker].profit.sum(),1)
    tick_prof.append(tot_profit)
    avg_tick_profit.append(round(tot_profit/occurence,1))
    profitable.append(round(len(df.loc[(df.ticker==ticker)&(df.Positive_return>0)])/occurence,5)*100)
stats=pd.DataFrame()
stats['ticker']=tickers
stats['occurences']=occurences
stats['profit_made_from_ticker']=tick_prof
stats['average_profit made/investment']=avg_tick_profit
stats['Positive_returns/Nb_of_investments']=profitable

In [11]:
stats

,ticker,occurences,profit_made_from_ticker,average_profit made/investment,Positive_returns/Nb_of_investments
0,XLY,17.0,15504.7,912.0,52.941
1,XLP,11.0,-13788.9,-1253.5,45.455
2,XLB,15.0,-23411.1,-1560.7,66.667
3,XLV,20.5,-27160.5,-1324.9,58.537
4,XLI,15.0,88923.0,5928.2,53.333
5,XLF,22.0,54282.7,2467.4,40.909
6,XLU,35.0,-106431.8,-3040.9,48.571
7,XLK,27.0,60132.6,2227.1,70.370
8,IYZ,15.0,103546.3,6903.1,73.333
9,XLE,55.0,333979.1,6072.3,58.182
10,XLRE,29.0,-64187.1,-2213.3,65.517

In [12]:
df.loc[df.ticker=='XLRE'].profit.sum()

-64187.08720016433

In [14]:
(1421389.03+1287089.17)/2000000

1.3542391